### ISSUE TITLE
Ability to get the PDF contents and inline response

### ISSUE THREAD

**Issue by gjm** [ismaelw/laratex#1]
I think two very useful features, that are very easy to implement, should be added: 
1. the ability to get the generated PDF contents as a string, for example through a `getContent()` method.
2. the ability to display the PDF inline, through an `inline()` method, just like the `download()` method downloads the generated PDF.

**Comment by ismaelw** [comment]
Hi Gonçalo

Thank you so much for your input! :)
Do you also have an Idea already, how you would implement those?
The getContent method should return a pdf base64 encoded string or literally the contents of the PDF?

The inline method is not quiet clear to me yet as this is very dependent on your environment I guess right? And there are alot of different possibilities like showing the PDF inside of a canvas etc.

**Comment by gjm** [comment]
@ismaelw, 

Starting by the end, the `inline` method would simply return a response with the `Content-Type: inline` header, very similar to the `download` method.

The `getContent`, I think, would return the raw PDF. But why not have both `getContent` and `getBase64Content`? They would simply return the contents of the generated file, raw and base64 encoded.

**Comment by ismaelw** [comment]
Hi @gjm,

The inline Method could actually just return the following:
`return \Response::file($pdfPath, ['Content-Type' => 'application/pdf','Content-Disposition' => 'inline; filename="'.basename($pdfPath).'"']);`

Like this you would return the pdf inline. I just tested this with a get request right now. I might need further testing to be able to post data that are allowing you to dynamically create pdfs.

Do you think that could work?

**Comment by ismaelw** [comment]
Hi @gjm 

I just updated the package. Would you mind testing it too on your side?

There are two new methods now: inline and content.

For inline you can just pass a string with a filename `->inline('filename.pdf');`
For content you can pass a string with `raw` or `base64` like this: `->content('base64');`

Does this resolve your request?

**Comment by gjm** [comment]
Works great! Thanks for your support!

**Comment by ismaelw** [comment]
Hi @gjm 

Thanks for your feedback! :)
Can I close this festure request?

**Comment by gjm** [comment]
Yes, I'm satisfied.

**Comment by ismaelw** [comment]
Thank you so much for your request and your testing!
