### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by orcankolan** [ismaelw/laratex#15]
ismaelw/laratex dev-main requires illuminate/support 5.4.x|5.5.X|5.6.X|5.7.X|5.8.X|^6.0|^7.0|^8.0|^9.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev].
    - Only one of these can be installed: illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, 10.x-dev], laravel/framework[v10.0.0, 10.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.

**Comment by ismaelw** [comment]
Hi @orcankolan 

Thank you very much for opening the issue.
Let me check the dependencies for Laravel 10 and try it out myself

**Comment by ismaelw** [comment]
Hi @orcankolan 

Please try the current release. I was able to install the package in Laravel 10.

**Comment by orcankolan** [comment]
Ok no issues here. Thank you so much :)
