### ISSUE TITLE
Package ismaelw/laratex at version  has a PHP requirement incompatible with your PHP version, 

### ISSUE THREAD

**Issue by dhruva81** [ismaelw/laratex#2]
Hi 

 I am getting following exception when installing on server with PHP version 8.0.6

``` 
[InvalidArgumentException]
  Package ismaelw/laratex at version  has a PHP requirement incompatible with your PHP version, 
  PHP extensions and Composer version
```

Kindly upgrade this package to support PHP v8.

Thank you.

**Comment by ismaelw** [comment]
Hi @dhruva81 
I just pushed a new version. The only change for now should be the composer file.
Can you test it again?

Thank you so much for your feedback!

**Comment by dhruva81** [comment]
Thank you very much. 

The package is now installing on php v8.

**Comment by ismaelw** [comment]
Hi @dhruva81 

Thank you so much for testing and for Our feedback. I will close this incident. If you find yourself having issues using PHP 8 with my package just contact me :)
