### ISSUE TITLE
Can not create pdf on windows

### ISSUE THREAD

**Issue by zillion42** [ismaelw/laratex#20]
Hi,

I have texlive installed in
C:\texlive\2023\bin\windows
I also added this to my path environment variable, running pdflatex in the cmd prompt works.

If I run
`return (new LaraTeX)->dryRun();`

with default config/laratex.php:
```
<?php

return [
	// bin path to your pdflatex installation | use 'which pdflatex' on a linux system to find out which is the path to your pdflatex installation
	'binPath' => 'pdflatex',

	// Folder in your storage folder where you would like to store the temp files created by LaraTeX
	'tempPath' => 'app',

	// boolean to define if log, aux and tex files should be deleted after generating PDF
	'teardown' => false,
];
```

I get a Str::random(10) file 
1 x vr0E5B8
1 x vr0E5B8.log
1 x vr0E5B8.aux

in my app directory

The log reads:
```
Output written on D:\Apache24_htdocs\project\storage
\app/vr0E5B8.pdf (1 page, 35744 bytes).
PDF statistics:
 29 PDF objects out of 1000 (max. 8388607)
 17 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```
but the file is not there, it's also not downloaded automatically.

I already tried all combinations of
```
	// Folder in your storage folder where you would like to store the temp files created by LaraTeX
	'tempPath' => 'app/',
        'tempPath' => 'app//',
	'tempPath' => 'app\',
        'tempPath' => 'app\\',
	'tempPath' => 'app',
```
None seems to work. 

If I rename vr0E5B8 into vr0E5B8.tex, I can double click open it with texworks and compile it just fine.

What am I doing wrong?

Running Win10 Pro, 22H2, 19045.2728 with Apache 2.4 (Xampp), PHP Version => 7.4.7

**Comment by zillion42** [comment]
EDIT:
I step by step debugged the whole process now. 

The Pdf is in fact created, but it won't download in the response. It shows and empty chrome tab, later the:
```
register_shutdown_function(function () use ($tmpfname) {
            if (File::exists($tmpfname . '.pdf')) {
                File::delete($tmpfname . '.pdf');
            }
        });
```
deletes the file...
Just tried with Firefox, same result.

**Comment by zillion42** [comment]
I also created the tex blade and tried:
```
return (new LaraTeX('latex.tex'))->with([
            'Name' => 'John Doe',
            'Dob' => '01/01/1990',
            'SpecialCharacters' => '$ (a < b) $',
            'languages' => [
                'English',
                'Spanish',
                'Italian'
            ]
        ])->download('test.pdf');
```
I also tried inline('test.pdf');
If I try savePdf('C:\Users\User\Desktop') I get:
```
ErrorException
rename(D:\Apache24_htdocs\projects\storage\app\qnp1882.pdf,C:\Users\User\Desktop): Access denied (code: 5) 
```

**Comment by zillion42** [comment]
This works:

```
    /**
     * Download file as a response
     *
     * @param  string|null $fileName
     * @return Illuminate\Http\Response
     */
    public function download($fileName = null) {
        if (!$this->isRaw) {
            $this->render();
        }

        $pdfPath = $this->generate();
        if (!$fileName) {
            $fileName = basename($pdfPath);
        }

        if (file_exists($pdfPath)) {
            header('Content-type: application/pdf');
            header('Content-Disposition: attachment; filename="' . $fileName . '"');
            header('Content-Transfer-Encoding: binary');
            header('Content-Length: ' . filesize($pdfPath));
            header('Accept-Ranges: bytes');
            @readfile($pdfPath);
        }
    }
```

but not using response. 👎

**Comment by ismaelw** [comment]
> I also created the tex blade and tried:
> 
> ```
> return (new LaraTeX('latex.tex'))->with([
>             'Name' => 'John Doe',
>             'Dob' => '01/01/1990',
>             'SpecialCharacters' => '$ (a < b) $',
>             'languages' => [
>                 'English',
>                 'Spanish',
>                 'Italian'
>             ]
>         ])->download('test.pdf');
> ```
> 
> I also tried
> 
> ```
> ->inline('test.pdf'); 
> ->content();
> ```
> 
> neither works.
> 
> If I try ->savePdf('C:\Users\User\Desktop') I get:
> 
> ```
> ErrorException
> rename(D:\Apache24_htdocs\projects\storage\app\qnp1882.pdf,C:\Users\User\Desktop): Access denied (code: 5) 
> ```

Saving a file outside of your laravel app is not working out of the box and security-wise also not recommended. The savePdf method can be used if you want each pdf saved somewhere inside of your laravel app storage. Note: This comment is just a side-note. I am trying to think about other reasons why your PDF generation doesn't work in Windows

**Comment by ismaelw** [comment]
Hi @zillion42 

I prepared my windows system now in the following way:

- XAMPP with PHP 8.1
- Windows 11
- Laravel 10
- texlive 2023

First I was able to figure out that after adding the texlive path to my PATH environment variable did not help, as `phpinfo()` didn't recognized the change. So inside some log files on my system I was able to find out that "pdflatex" was not recognized as a command.

Using the absolute path `C:\texlive\2023\bin\windows\pdflatex.exe` in the config `binPath` did the trick in that moment.

After some research I got tired and restarted my machine. After that `phpinfo()` did actually have the texlive path from my PATH system environment variable in the PHP Path variable.

Changing back the `binPath` to `pdflatex` then made me beeing able to run dryrun and a PDF has been downloaded successfully.

So my question to you would be: 

- Did you restart your computer after changing your PATH environment variable?
- If yes, can you make a route that just says `dd(phpinfo());` inside laravel and check the PATH variable there and confirm that the path is there?
- And if the path is there and it still doesn't work, can you try to add the absolute path to your binPath config?

Thank you so much for your feedback.

Kind regards,
Ismael

**Comment by zillion42** [comment]
Hi,

_Did you restart your computer after changing your PATH environment variable?_
Sure, more than once, but actually in windows it is enough to restart the console (cmd prompt) after adding the path. I don't quite understand why you were searching the texlive path in phpinfo, but I guess the php PATH should be the same as the system PATH.
I never had any issues with PHP finding pdlatex.exe, that was never a problem. But just for testing purposes I also added the complete path which is C:\texlive\2023\bin\windows\pdflatex.exe - That works just the same.

Also like I said, laratex actually generates the pdf, so it definitely works. 

The problem is that the response does not download the file, before it gets deleted by the shutdown function. So the pdf is there for a brief moment, then gets deleted again. The response however does not trigger a file download.

I'm suspecting more something not working with:
```
\Event::dispatch(new LaratexPdfWasGenerated($fileName, 'download', $this->metadata));

        return \Response::download($pdfPath, $fileName, [
            'Content-Type' => 'application/pdf',
        ]);
```

Anyway Thank you so much for testing this so quick on a windows machine. Please note, I am not using PHP 8, but 7.4

**Comment by ismaelw** [comment]
My apologies. You are right. You did mention the PDF gets generated.

What I couldn't read from your messages is if any exception is thrown?

Or everything seems to be fine but nothing happens?

If you wish I can continue the troubleshooting or we try to troubleshoot it on your end together?

I remember having someone that was able to use laratex using windows and PHP 7.4 so that should also be no issue here.

**Comment by zillion42** [comment]
Since unfortunately you can not reproduce the issue, it would make sense to debug it on my end.., There is no exception thrown unfortunately, I will provide some screenshots.

**Comment by ismaelw** [comment]
Also I did try using a mix of slashes in windows. So in the same path a mix of back- and forwardslashes. Windows is actually pretty good in handling this. But to try it would be maybe an option to replace everything with forwardslashes.

**Comment by ismaelw** [comment]
If all this seems to work just fine I am thinking if we should focus on the response which is Laravel specific and not LaraTeX specific. I am just thinking about that because on Line 203 everything seems to be fine and as to my understanding a PDF file exists inside your storage/app folder. 

Maybe a stupid question. but did you ever try to put a random file into your storage path and download it using the Response class?

**Comment by zillion42** [comment]
Now that you say it I haven't actually. I just looked at how I download PhpOffice Excel files.

```
        // Redirect output to a client’s web browser (Xlsx)
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="' . $filename . '.xlsx"');
        header('Cache-Control: max-age=0');
        // If you're serving to IE 9, then the following may be needed
        header('Cache-Control: max-age=1');

        // If you're serving to IE over SSL, then the following may be needed
        header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
        header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
        header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
        header('Pragma: public'); // HTTP/1.0

        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $writer->save('php://output');
        exit;
```

But I tested it now, and this also works without any problems. 
```
        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $writer->save($path = storage_path('download.xlsx'));
        return response()->download($path, $filename . '.xlsx')->deleteFileAfterSend();
```
$writer belongs to PhpOffice
```
namespace PhpOffice\PhpSpreadsheet;

use PhpOffice\PhpSpreadsheet\Reader\IReader;
use PhpOffice\PhpSpreadsheet\Shared\File;
use PhpOffice\PhpSpreadsheet\Writer\IWriter;
```

**Comment by ismaelw** [comment]
This is actually getting super weird. So at the moment everything seems to works and should be working but it just doesn't.
How I cannot replicate the issue on my side it is quiet hard to think of something without having a hands-on.

Things I would like to test would be
- Check the return value in your controller from the call using dd();
- Return a Response using no header at all

If it is an option for you we can maybe even arrange a Teams call to get this working for you.

**Comment by ismaelw** [comment]
Your response looks exactly the same like mine on my windows machine.

Another question: do you have the php_fileinfo PHP extension enabled? I guess probably yes but excluding always helps.
Or in general I am thinking about uncatched exceptions from the apache and php front.

So maybe you could also check things like the "max_execution_time" runtime setting in PHP, and check the apache error_log in your xampp setup. I am just trying to think of all the issues I had in all my time and come up with a possible cause

**Comment by ismaelw** [comment]
Wait a minute.

After checking your code I realized one thing. 

```
public function download(){

        return (new LaraTeX('latex.tex'))->with([
            'Name' => 'John Doe',
            'Dob' => '01/01/1990',
            'SpecialCharacters' => '$ (a < b) $',
            'languages' => [
                'English',
                'Spanish',
                'Italian'
            ]
        ])->download('test.pdf');
    }
    
    public function export(Request $request) {

        $this->download();
        
    }
```

Your download method returns a file but your export method doesn't actually return anything.

Can you try changing 
`$this->download();`

to `return $this->download();`

**Comment by zillion42** [comment]
Hi,
I actually have quite some work ahead of me at the moment, I also think it's weird by now.
```
max_execution_time=1440
extension=fileinfo
```
WOW

> Your download method returns a file but your export method doesn't actually return anything.
> 
> Can you try changing `$this->download();`
> 
> to `return $this->download();`
> 
> EDIT: I was able to replicate the white empty tab when I removed the `return` on my end. In that case I am not actually returning a file.

That was it... omg, thx for all the trouble. I was beginning to suspect it must be something really stupid on my part. I think I'll donate you a coffee for this. 
Thank so much again.

**Comment by ismaelw** [comment]
haha amazing. Well that happens. Whenever I have an issue like this I end up face-palming myself for wasting valuable time on a syntax or thinking error.

You are very welcome - and I am here if there is anything else I can help you with! 🥳

**Comment by zillion42** [comment]
I'm sorry to bother you so much, but I have another question real quick. Should I open another issue?

I have this kind of array each entry has a model and a collection:
 
![2023-03-23 11_52_55-Start](https://user-images.githubusercontent.com/36650866/227182144-7dd5bb93-8226-411c-b02e-e1a0d64199d0.jpg)

I'm passing it to the tex blade like so:
`return (new LaraTeX('clerk.clerk_export_tex'))->with($daten)->download('test.pdf');`

and I get
![2023-03-23 11_53_35-🧨 Undefined variable_ daten (View_ D__Webappsrv_c_httpd_Apache24_htdocs_kranken](https://user-images.githubusercontent.com/36650866/227182609-aa4414b3-f306-4d1a-bf0a-bc62719c2130.jpg)

**Comment by ismaelw** [comment]
@zillion42 no worries.

Please reference this in a new issue and we can look at it together :)
