### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by drjermy** [ismaelw/laratex#26]
I wonder whether you'd consider bumping versions to support Laravel 11.

Problem 1
    - illuminate/support[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.2.16) does not satisfy that requirement.
    - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.2.16) does not satisfy that requirement.
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.2.16) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.2.16) does not satisfy that requirement.
    - Root composer.json requires ismaelw/laratex ^1.1 -> satisfiable by ismaelw/laratex[v1.1.0, ..., v1.2.2].
    - Conclusion: don't install laravel/framework v11.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.7 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.0 (conflict analysis result)
    - ismaelw/laratex[v1.1.0, ..., v1.2.2] require illuminate/support ^5.0|^6.0|^7.0|^8.0|^9.0|^10.0 -> satisfiable by illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev].

**Comment by ismaelw** [comment]
Hi @drjermy 

Yes of course! I was not really checking and didn't realize that Laravel 11 was already out.
I will definitely do that soon.
