### ISSUE TITLE
Class "Event" not found

### ISSUE THREAD

**Issue by ahmadnakouzi** [ismaelw/laratex#28]
After installing texlive-full  and the laratex package, I'm facing the following issue when calling this function:

function:
-----------
public function laraTexTest()
    {
        return (new LaraTeX)->dryRun();
    }
    
    
Error: 
------
Class "Event" not found in file /var/www/app/vendor/ismaelw/laratex/src/LaraTeX.php on line 221

laravel version: 10
PHP version: 8.2

**Comment by ismaelw** [comment]
Hi @ahmadnakouzi 

Let me look into it. I will gove you feedback soon!

Kind regards,
Ismael

**Comment by baseljd** [comment]
I faced the same issue and fixed it **temporary** by changing two things the file vendor/ismaelw/laratex/src/LaraTeX.php on my server.

  1. Add line:  use Illuminate\Support\Facades\Event;
  
  2. Event:: instead of \Event:: on line 221

I hope we can find a better solution.

**Comment by ismaelw** [comment]
> I faced the same issue and fixed it **temporary** by changing two things the file vendor/ismaelw/laratex/src/LaraTeX.php on my server.
> 
> 
> 
>   1. Add line:  use Illuminate\Support\Facades\Event;
> 
>   
> 
>   2. Event:: instead of \Event:: on line 221
> 
> 
> 
> I hope we can find a better solution.

Hi @baseljd 

I read something about facade changes in Laravel 10. So your temporary bugfix is probably the correct fix for it. I will implement this and create a new release.

Kind regards,
Ismael

**Comment by ahmadnakouzi** [comment]
I have tried the temporary changes mentioned above, but I'm still facing a new issue:
sh: line 0: exec: pdflatex: not found.

so don't think it is a solution

**Comment by ismaelw** [comment]
tztöutzzttzztztt
ä
> so don't think it is the solution

Hi @ahmadnakouzi 

Thank you for your message.
I guess this issue is another one. What system are you running your laravel application on? Windows or Linux? Do you have access to the console? If yes, can you run pdflatex directly without passing the path to the executable?

**Comment by ahmadnakouzi** [comment]
Hi @ismaelw 
locally using MacBook (doesn't work with the temporary fixes)
Server using Linux Ubuntu (worked with the temporary fixes mentioned above)

**Comment by ismaelw** [comment]
> Hi @ismaelw 
> 
> locally using MacBook (doesn't work with the temporary fixes)
> 
> Server using Linux Ubuntu (worked with the temporary fixes mentioned above)

On your MacBook in terminal, if you just type in pdflatex and press enter - does it run pdflatex? If not then maybe you have to pass the absolute path to your pdflatex installtion. And if that is the case - you would have to add the absolute path to the binPath config file of LaraTeX

**Comment by ismaelw** [comment]
@baseljd @ahmadnakouzi 

The bug fix is implemented and a new release 1.2.4 has been created. 
@ahmadnakouzi For further support on your local machine using MacOS please provide more details on my question in my other comment.

Kind regards,
Ismael

**Comment by ahmadnakouzi** [comment]
Hello @ismaelw 
Thanks for your fast response.

Alright, I will check it on my server.

I have tried running pdflatex locally on my MacBook and here is the result.

<img width="699" alt="Screenshot 2024-10-14 at 11 56 08 AM" src="https://github.com/user-attachments/assets/84c56b57-1e67-4868-8ea2-6cf7e3a9a280">

**Comment by ismaelw** [comment]
> Hello @ismaelw Thanks for your fast response.
> 
> Alright, I will check it on my server.
> 
> I have tried running pdflatex locally on my MacBook and here is the result.
> 
> <img alt="Screenshot 2024-10-14 at 11 56 08 AM" width="699" src="https://private-user-images.githubusercontent.com/20565244/376171249-84c56b57-1e67-4868-8ea2-6cf7e3a9a280.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTY5MzEsIm5iZiI6MTcyODg5NjYzMSwicGF0aCI6Ii8yMDU2NTI0NC8zNzYxNzEyNDktODRjNTZiNTctMWU2Ny00ODY4LThlYTItNmNmN2UzYTlhMjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA5MDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZWE5YTU0NDhiNGQyZWY0NDRkNjgzNGI1NzQwYmI1ZDFjMzJjZDIyMTQ0MTFhZTViOGEwZWY2ZTlkYThkOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DM5SeLN3N7CwTvXjm_5uePzFiyi9ARIAqpD57Xe7P2g">

Hi @ahmadnakouzi 

I just remember something. I had a similar issue in my Windows machine.
What I did realize is, that for whatever reason, my PHP PATH environment variable was not the same as my local PATH environment variables. Therefore the webserver was not able to find the pdflatex executable.

What I ended up doing was moving the pdflatex Path from my config file to the .env file and referencing that env Variable in my config file so that I can have a workaround on my local machine but still use the normal "pdflatex" setting in my production environment on my linux server.

Config file:
```<?php

return [
	// bin path to your pdflatex installation | use 'which pdflatex' on a linux system to find out which is the path to your pdflatex installation
	'binPath' => env('LATEX_PATH', ''),

	// Folder in your storage folder where you would like to store the temp files created by LaraTeX
	'tempPath' => 'app/temp/',

	// boolean to define if log, aux and tex files should be deleted after generating PDF
	'teardown' => true,
];```

.env file:
```
LATEX_PATH=/absolute/path/to/pdflatex
```

Can you try locally what happens if you (not using the .ENV file just yet) pass the absolute path to pdflatex on your MacBook to see if that would work?

**Comment by ismaelw** [comment]
Hi @ahmadnakouzi 

Have you been able to test and troubleshoot your other issue?

Kind regards,
Ismael
