### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by orcankolan** [ismaelw/laratex#4]
Cannot require laratex with laravel 9

**Comment by ismaelw** [comment]
Hi @orcankolan 

Thank you so much for your opened issue.
Give me a few hours time so that I can test this plugin with Laravel 9 and then Update it

**Comment by orcankolan** [comment]
Very very cool and useful package. I hope you can manage to make it work with Laravel 9

**Comment by ismaelw** [comment]
The new composer changes have been published right now. I will leave this issue open until I have further news from you or if I'm sure that there are no broken functions due to the new Laravel 9 version.

**Comment by ismaelw** [comment]
Hi @orcankolan 

I couldn't find anything in the documentation that would be an issue with the current code so with the composer changes we should be good to go.

I allow myself to close this issue now. 

Kind regards,
Ismael
